display_name: FireBoxTransfer
packager: FireBoxTransfer
packagerEmail: unset@fireboxtransfer.invalid
buildArch: x86_64
license: MIT

icon: assets/img/logo-512.png

requires:
  - libappindicator
  - xdg-user-dirs

keywords:
  - Sharing
  - LAN
  - Files

generic_name: Transfer and manage files between your PC and phone over your local network
summary: Transfer and manage files between your PC and phone with FireBoxTransfer
group: Applications/Utilities

categories:
  - GTK
  - FileTransfer
  - Utility

startup_notify: true
