// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'cancel.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'stream.dart';
part 'http.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `message`, `require_remote_fs`, `resolve_file_content`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RemoteReadState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `from`, `from`

/// Creates an HTTP client.
///
/// `expected_fingerprint` pins the peer to the certificate with that SHA-256
/// fingerprint (uppercase hex). It is enforced during the TLS handshake, so a
/// peer that does not present the expected certificate never receives the
/// request. Pass `None` only for discovery, where the peer is not known yet.
RsHttpClient createClient({
  required String privateKey,
  required String cert,
  required LsHttpClientVersion version,
  String? expectedFingerprint,
  int? timeoutMs,
}) => RustLib.instance.api.crateApiHttpCreateClient(
  privateKey: privateKey,
  cert: cert,
  version: version,
  expectedFingerprint: expectedFingerprint,
  timeoutMs: timeoutMs,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsHttpClient>>
abstract class RsHttpClient implements RustOpaqueInterface {
  Future<void> cancel({required ProtocolType protocol, required String ip, required int port, required String sessionId});

  Future<PrepareUploadResult> prepareUpload({
    required ProtocolType protocol,
    required String ip,
    required int port,
    required PrepareUploadRequestDto payload,
    String? publicKey,
    String? pin,
    required RsCancellationToken cancelToken,
  });

  Future<ResultWithPublicKeyRegisterResponseDto> register({
    required ProtocolType protocol,
    required String ip,
    required int port,
    required RegisterDto payload,
  });

  Future<RemoteFsEntry> remoteFsCreateDirectory({required String ip, required int port, required RemoteFsCreateDirectoryRequest request});

  Future<void> remoteFsDelete({required String ip, required int port, required RemoteFsDeleteRequest request});

  Future<RemoteFsListResponse> remoteFsList({required String ip, required int port, required RemoteFsListRequest request});

  Future<RemoteFsEntry> remoteFsMetadata({required String ip, required int port, required RemoteFsLocation target});

  Future<RemoteFsEntry> remoteFsMove({required String ip, required int port, required RemoteFsMoveRequest request});

  /// Opens a pull-based remote read. Dart calls [RsRemoteReadStream::next_chunk]
  /// for each chunk, which provides natural backpressure and bounds memory.
  Future<RsRemoteReadStream> remoteFsOpenRead({required String ip, required int port, required RemoteFsLocation target});

  Future<RemoteFsEntry> remoteFsRename({required String ip, required int port, required RemoteFsRenameRequest request});

  Future<List<RemoteFsRoot>> remoteFsRoots({required String ip, required int port});

  /// Streams local content to a remote authorized path. The source may be a
  /// Dart stream, a path or an owned Android descriptor; exactly one is set.
  Stream<RsRemoteFsWriteEvent> remoteFsWrite({
    required String ip,
    required int port,
    required RemoteFsLocation target,
    required bool overwrite,
    Dart2RustStreamReceiver? binary,
    String? path,
    int? fileDescriptor,
    required BigInt contentLength,
    required RsCancellationToken cancelToken,
  });

  /// Uploads a single file, emitting [RsUploadEvent]s on [sink].
  ///
  /// Failures are emitted as [RsUploadEvent::Failed] instead of being
  /// returned: flutter_rust_bridge discards the returned `Result` of
  /// functions taking a [StreamSink], so a returned error would become an
  /// uncaught async error killing the calling isolate.
  Stream<RsUploadEvent> upload({
    required ProtocolType protocol,
    required String ip,
    required int port,
    String? publicKey,
    required String sessionId,
    required String fileId,
    required String token,
    Dart2RustStreamReceiver? binary,
    String? path,
    int? fileDescriptor,
    required BigInt contentLength,
    required RsCancellationToken cancelToken,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsRemoteReadStream>>
abstract class RsRemoteReadStream implements RustOpaqueInterface {
  BigInt? contentLength();

  String? contentType();

  Future<Uint8List?> nextChunk({required RsCancellationToken cancelToken});
}

enum LsHttpClientVersion {
  v2,
  v3,
}

class PrepareUploadResult {
  final int statusCode;
  final PrepareUploadResponseDto? response;

  const PrepareUploadResult({
    required this.statusCode,
    this.response,
  });

  @override
  int get hashCode => statusCode.hashCode ^ response.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrepareUploadResult && runtimeType == other.runtimeType && statusCode == other.statusCode && response == other.response;
}

class ResultWithPublicKeyRegisterResponseDto {
  final String? publicKey;
  final RegisterResponseDto body;

  const ResultWithPublicKeyRegisterResponseDto({
    this.publicKey,
    required this.body,
  });

  @override
  int get hashCode => publicKey.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResultWithPublicKeyRegisterResponseDto && runtimeType == other.runtimeType && publicKey == other.publicKey && body == other.body;
}

@freezed
sealed class RsHttpClientError with _$RsHttpClientError implements FrbException {
  const RsHttpClientError._();

  const factory RsHttpClientError.statusCode({
    required int status,
    String? message,
  }) = RsHttpClientError_StatusCode;
  const factory RsHttpClientError.reqwest(
    String field0,
  ) = RsHttpClientError_Reqwest;
  const factory RsHttpClientError.json(
    String field0,
  ) = RsHttpClientError_Json;
  const factory RsHttpClientError.io(
    String field0,
  ) = RsHttpClientError_Io;
  const factory RsHttpClientError.other(
    String field0,
  ) = RsHttpClientError_Other;
}

@freezed
sealed class RsRemoteFsClientError with _$RsRemoteFsClientError implements FrbException {
  const RsRemoteFsClientError._();

  const factory RsRemoteFsClientError.remote({
    required int status,
    required RemoteFsErrorCode code,
    required String message,
  }) = RsRemoteFsClientError_Remote;
  const factory RsRemoteFsClientError.setup(
    String field0,
  ) = RsRemoteFsClientError_Setup;
  const factory RsRemoteFsClientError.reqwest(
    String field0,
  ) = RsRemoteFsClientError_Reqwest;
  const factory RsRemoteFsClientError.json(
    String field0,
  ) = RsRemoteFsClientError_Json;
  const factory RsRemoteFsClientError.io(
    String field0,
  ) = RsRemoteFsClientError_Io;
  const factory RsRemoteFsClientError.invalidRequest({
    required RemoteFsErrorCode code,
  }) = RsRemoteFsClientError_InvalidRequest;
  const factory RsRemoteFsClientError.invalidResponse() = RsRemoteFsClientError_InvalidResponse;
  const factory RsRemoteFsClientError.cancelled() = RsRemoteFsClientError_Cancelled;
  const factory RsRemoteFsClientError.other(
    String field0,
  ) = RsRemoteFsClientError_Other;
}

@freezed
sealed class RsRemoteFsWriteEvent with _$RsRemoteFsWriteEvent {
  const RsRemoteFsWriteEvent._();

  const factory RsRemoteFsWriteEvent.progress({
    required BigInt bytesWritten,
  }) = RsRemoteFsWriteEvent_Progress;
  const factory RsRemoteFsWriteEvent.completed({
    required BigInt bytesWritten,
  }) = RsRemoteFsWriteEvent_Completed;
  const factory RsRemoteFsWriteEvent.failed({
    required RsRemoteFsClientError error,
  }) = RsRemoteFsWriteEvent_Failed;
}

@freezed
sealed class RsUploadEvent with _$RsUploadEvent {
  const RsUploadEvent._();

  /// The upload progress as a fraction (0.0 to 1.0). Throttled.
  const factory RsUploadEvent.progress({
    required double progress,
  }) = RsUploadEvent_Progress;

  /// The upload failed. Always the last event of the stream.
  const factory RsUploadEvent.failed({
    required RsHttpClientError error,
  }) = RsUploadEvent_Failed;
}
